backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to main)
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "site" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{lang}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Meta title", name: "meta_title", widget: "string"}
      - {label: "Meta description", name: "meta_description", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Language", name: "lang", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
media_folder: 'uploads'
